name: pymdwizard
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - cryptography
  - numpy
  - pandas
  - geopandas
  - gdal
  - matplotlib
  - folium
  - fiona
  - shapely
  - pyproj
  - lxml
  - openpyxl
  - jupyterlab
  - ipywidgets
  - scikit-learn
  - requests
  - beautifulsoup4
  - pyyaml
  - pyqt=5
  - qtpy
  - pip:
    - pyqtwebengine
    - sciencebasepy
    - pip-system-certs